version: '3'
services:
  mysql_db:
    env_file:
      - .env
    image: mysql
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=root
    ports:
      - 3308:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
  app:
    depends_on:
      - mysql_db
    build: .
    container_name: cons-node
    environment:
      - DATABASE_URL=mysql://root:1234@mysql_db:3308/db_food?schema=public
    ports:
      - 3002:8080
    networks:
      - node-network
volumes:
  mysql_db:
    driver: local
networks:
  node-network:


# docker-compose up -d
